In [2]:
import numpy as np

In [15]:
arr1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [8, 9, 10]], dtype=np.int64)
arr2 = np.array([[14, 2, 3],
               [3, 5, 6],
               [8, 90, 1]], dtype= np.int64)

print(f'Original array one:\n {arr1} \n\n')
print(f'Original array two:\n {arr2} \n\n')

print(f'Addition of elements:\n {np.sum(arr1)}')
print(f'Addition of arrays:\n {np.add(arr1, arr2)}')
print(f'squareRoot:\n {np.sqrt(arr1)}')



Original array one:
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 


Original array two:
 [[14  2  3  1]
 [ 3  5  6  2]
 [ 8 90  1  5]] 




ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 